
import Spinner from '@/components/layout/spinner/spinner';
import NoData from '@/components/layout/Nodata';

export default {
    components:{
        Spinner,
        NoData
    },
    props: {
        NoData: { type: Boolean, default: false},
        height: { type: [Number], default: 0 },
        loading: { type: Boolean, default: false },
        employeeName: { type: String, default: "N/a" },
        position: { type: String, default: "N/a" },
        dateHired: { type: String, default: "N/a" },
        teacherLevel: { type: String, default: "N/a" },
        classRate: { type: [String, Number], default: "N/a" },
        employeeType: { type: String, default: "N/a" },
        payrollRegister: { type: String, default: "N/a" },
        payPeriod: { type: String, default: "N/a" },
        payDate: { type: String, default: "N/a" },
        PHIC: { type: String, default: "N/a" },
        HDMF: { type: String, default: "N/a" },
        TIN: { type: String, default: "N/a" },
        SSS: { type: String, default: "N/a" },
        serviceFee: { type: [String,Number], default: "0.00" },
        trainingFee: { type: [String,Number], default: "0.00" },
        observationFee: { type: [String,Number], default: "0.00" },
        salaryAdjustment: { type: String, default: "N/a" },
        accountNumber: { type: String, default: "N/a" },
        bankName: { type: String, default: "N/a" },
        attendanceIncentives: { type: [String,Number], default: "0.00" },
        performanceBonus: { type: [String,Number], default: "0.00" },
        partialReferralBonus: { type: [String,Number], default: "0.00" },
        classIncentive: { type: [String,Number], default: "0.00" },
        perfomanceImprovement: { type:  [String,Number], default: "0.00"},
        transferredClass: { type: [String,Number], default: "0.00" },
        less25Minutes: { type: [String,Number], default: "0.00" },
        deductionsClass: { type: [String,Number], default: "0.00" },
        callin: { type: [String,Number], default: "0.00" },
        awol: { type: [String,Number], default: "0.00" },
        less25MinutesDeduction: { type: [String,Number], default: "0.00" },
        grossIncome: { type: [String,Number], default: "0.00" },
        totalDeduction: { type: [String,Number], default: "0.00" },
        NETPAY: { type: [String,Number], default: "0.00" },
        employeeSignature: { type: String, default: "" },
        preparedBy: { type: String, default: "" },
        totalCourseIncentives: { type: [String, Number], default: "sd" },
        lateShift: { type: [String,Number], default: "0.00" },
        lateClass: { type: [String,Number], default: "0.00" },
        late_20: { type: [String,Number], default: "0.00" },
        late_10: { type: [String,Number], default: "0.00" },
        video_duration_deduction: { type: [String,Number], default: "0.00" },
        g_30_transferred: { type: [String,Number], default: "0.00" },
        l_30_transferred: { type: [String,Number], default: "0.00" },
        sub_class_rate: { type: [String,Number], default: "0.00" },
        week_end_rate: { type: [String,Number], default: "0.00" },
    }
}